CREATE TABLE UNIVERSITYVIEW (
    UNIVERSITYID INTEGER NOT NULL,
    VIEWCOUNT INTEGER DEFAULT 0,
    PRIMARY KEY (UNIVERSITYID),
    FOREIGN KEY (UNIVERSITYID) REFERENCES UNIVERSITY (ID) ON DELETE CASCADE);