package com.eapproject.PresentationLayer.StatisticsView;


import java.awt.Font;

import javax.swing.GroupLayout;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author kamoz
 */
public class StatisticsView extends javax.swing.JPanel {

    /**
     * Creates new form StatisticsForm
     */
    public StatisticsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topSeperator = new javax.swing.JSeparator();
        statisticsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statsTable = new javax.swing.JTable();
        bottomSeperator = new javax.swing.JSeparator();
        exportButton = new javax.swing.JButton();



        mainPanel.setBackground(new java.awt.Color(252, 252, 242));
        mainPanel.setForeground(new java.awt.Color(252, 252, 242));

        this.setPreferredSize(new java.awt.Dimension(1050, 960)); // Large preferred size for the panel

        mainPanel.setPreferredSize(new java.awt.Dimension(1050, 960)); // Set main panel size (width and height)

        topSeperator.setBackground(new java.awt.Color(223, 109, 35));
        topSeperator.setForeground(new java.awt.Color(223, 109, 35));
        topSeperator.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        statisticsLabel.setBackground(new java.awt.Color(223, 109, 35));
        statisticsLabel.setFont(new java.awt.Font("Segoe UI", 1, 46)); // NOI18N
        statisticsLabel.setForeground(new java.awt.Color(223, 109, 35));
        statisticsLabel.setText("Statistics");

        statsTable.setBackground(new java.awt.Color(255, 255, 255));
        statsTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(223, 109, 35), 2));
        statsTable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        statsTable.setForeground(new java.awt.Color(96, 59, 6));

        statsTable.getTableHeader().setReorderingAllowed(false);

// Αλλαγή χρώματος στα headers
        // Table Grid customization
        statsTable.setShowGrid(false);
        statsTable.setGridColor(new java.awt.Color(223, 109, 35)); // Grid lines in orange
        statsTable.setIntercellSpacing(new java.awt.Dimension(0, 0)); // Remove space between cells
        statsTable.getTableHeader().setBackground(new java.awt.Color(223, 109, 35)); // Πορτοκαλί χρώμα
        statsTable.getTableHeader().setForeground(new java.awt.Color(255, 255, 255)); // Λευκό κείμενο
        statsTable.getTableHeader().setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // Μεγαλύτερη γραμματοσειρά
        statsTable.setCellSelectionEnabled(true);
        statsTable.setFocusable(false); // Disable focus (no direct editing)
        statsTable.setDefaultEditor(Object.class, null); // Disable editor for all cells
        statsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION); // Allow only single row selection
        statsTable.setRowSelectionAllowed(true); // Enable row selection, but not column selection
        statsTable.setColumnSelectionAllowed(false); // Disable column selection
        // Custom font and renderer for table cells


        // Selection customization
        statsTable.setSelectionBackground(new java.awt.Color(187, 124, 82, 200)); // Background color for selected row
        statsTable.setSelectionForeground(java.awt.Color.WHITE); // White text color for selected row

        // Row height adjustment for better visibility
        statsTable.setRowHeight(40); // Increased row
        statsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {"Harvard University", 1200},
                        {"Stanford University", 950},
                        {"MIT", 1100},
                        {"University of Oxford", 890},
                        {"University of Cambridge", 870},
                        {"ETH Zurich", 740},
                        {"National University of Singapore", 680},
                        {"University of Tokyo", 720}
                },
                new String [] {
                        "University", "Views"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        statsTable.setFillsViewportHeight(true);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER); // Center text in cells
        centerRenderer.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 28)); // Bold font for cells
        centerRenderer.setForeground(new java.awt.Color(139, 89, 61)); // Brown color for cell text

// Apply the custom renderer to all columns
        for (int i = 0; i < statsTable.getColumnCount(); i++) {
            statsTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        jScrollPane1.setViewportView(statsTable);

        bottomSeperator.setBackground(new java.awt.Color(223, 109, 35));
        bottomSeperator.setForeground(new java.awt.Color(223, 109, 35));

        exportButton.setBackground(new java.awt.Color(223, 109, 35));
        exportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exportButton.setForeground(new java.awt.Color(255, 255, 255));
        exportButton.setText("Export PDF");
        exportButton.setBorder(null);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(topSeperator, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bottomSeperator)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addContainerGap(500, Short.MAX_VALUE)
                                .addGap(100)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(420, 420, 420))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGap(420, 420, 420)
                                                .addComponent(statisticsLabel))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGap(416, 416, 416)
                                                .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(statisticsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGap(13)
                                .addComponent(topSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)

                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)

                                .addComponent(bottomSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40))

        );

        this.add(mainPanel);
        /* Create and display the form */

    }

    // Variables declaration - do not modify
    private javax.swing.JSeparator bottomSeperator;
    private javax.swing.JButton exportButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel statisticsLabel;
    private javax.swing.JTable statsTable;
    private javax.swing.JSeparator topSeperator;
    // End of variables declaration
}