CREATE TABLE UNIVERSITY_DOMAINS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    UNIVERSITY_ID INTEGER NOT NULL,
    DOMAIN VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (UNIVERSITY_ID) REFERENCES UNIVERSITY(ID) ON DELETE CASCADE
);